//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL_EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ToDoEntities : DbContext
    {
        public ToDoEntities()
            : base("name=ToDoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cat_Estatus> Cat_Estatus { get; set; }
        public virtual DbSet<Op_Tareas> Op_Tareas { get; set; }
    
        public virtual ObjectResult<Nullable<decimal>> RCSP_AddTarea(string titulo, string descripcion)
        {
            var tituloParameter = titulo != null ?
                new ObjectParameter("Titulo", titulo) :
                new ObjectParameter("Titulo", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("RCSP_AddTarea", tituloParameter, descripcionParameter);
        }
    
        public virtual int RCSP_DeleteTareas(Nullable<int> idTarea)
        {
            var idTareaParameter = idTarea.HasValue ?
                new ObjectParameter("IdTarea", idTarea) :
                new ObjectParameter("IdTarea", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RCSP_DeleteTareas", idTareaParameter);
        }
    
        public virtual ObjectResult<RCSP_GetTareaPendiComple_Result> RCSP_GetTareaPendiComple(Nullable<int> filtroIdEstatus)
        {
            var filtroIdEstatusParameter = filtroIdEstatus.HasValue ?
                new ObjectParameter("FiltroIdEstatus", filtroIdEstatus) :
                new ObjectParameter("FiltroIdEstatus", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RCSP_GetTareaPendiComple_Result>("RCSP_GetTareaPendiComple", filtroIdEstatusParameter);
        }
    
        public virtual int RCSP_UpdateEstatusTarea(Nullable<int> idTarea, Nullable<int> nuevoIdEstatus)
        {
            var idTareaParameter = idTarea.HasValue ?
                new ObjectParameter("IdTarea", idTarea) :
                new ObjectParameter("IdTarea", typeof(int));
    
            var nuevoIdEstatusParameter = nuevoIdEstatus.HasValue ?
                new ObjectParameter("NuevoIdEstatus", nuevoIdEstatus) :
                new ObjectParameter("NuevoIdEstatus", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RCSP_UpdateEstatusTarea", idTareaParameter, nuevoIdEstatusParameter);
        }
    }
}
