//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Op_Tareas
    {
        public int n_IdTarea { get; set; }
        public string c_Titulo { get; set; }
        public string c_Descripcion { get; set; }
        public int n_IdEstatus { get; set; }
        public bool b_Habilitado { get; set; }
    
        public virtual Cat_Estatus Cat_Estatus { get; set; }
    }
}
